# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluxx_crm}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hansen"]
  s.date = %q{2010-07-06}
  s.email = %q{fluxx@acesfconsulting.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
     "app/controllers/organizations_controller.rb",
     "app/models/organization.rb",
     "app/views/organizations/index.html.erb",
     "config/routes.rb",
     "lib/fluxx_crm.rb",
     "lib/fluxx_crm/engine.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Fluxx CRM Core}
  s.test_files = [
    "test/dummy/app/controllers/application_controller.rb",
     "test/dummy/app/helpers/application_helper.rb",
     "test/dummy/config/application.rb",
     "test/dummy/config/boot.rb",
     "test/dummy/config/environment.rb",
     "test/dummy/config/environments/development.rb",
     "test/dummy/config/environments/production.rb",
     "test/dummy/config/environments/test.rb",
     "test/dummy/config/initializers/backtrace_silencers.rb",
     "test/dummy/config/initializers/inflections.rb",
     "test/dummy/config/initializers/mime_types.rb",
     "test/dummy/config/initializers/secret_token.rb",
     "test/dummy/config/initializers/session_store.rb",
     "test/dummy/config/routes.rb",
     "test/fluxx_crm_test.rb",
     "test/integration/navigation_test.rb",
     "test/support/integration_case.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.3"])
      s.add_runtime_dependency(%q<formtastic-rails3>, [">= 0.9.10.0"])
      s.add_runtime_dependency(%q<haml>, [">= 3"])
      s.add_development_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_development_dependency(%q<thin>, [">= 1.2.7"])
      s.add_development_dependency(%q<json>, [">= 1.4.3"])
    else
      s.add_dependency(%q<fastercsv>, [">= 1.5.3"])
      s.add_dependency(%q<formtastic-rails3>, [">= 0.9.10.0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_dependency(%q<thin>, [">= 1.2.7"])
      s.add_dependency(%q<json>, [">= 1.4.3"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 1.5.3"])
    s.add_dependency(%q<formtastic-rails3>, [">= 0.9.10.0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<jsmin>, [">= 1.0.1"])
    s.add_dependency(%q<thin>, [">= 1.2.7"])
    s.add_dependency(%q<json>, [">= 1.4.3"])
  end
end

