# Sample localization file for English. Add more files in this directory for other locales.
# See http://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale for starting points.

en:
  hello: "Hello world"
  insta_successful_update: "%{name} was successfully updated."
  insta_successful_create: "%{name} was successfully created."
  insta_successful_delete: "%{name} was successfully deleted."
  insta_unsuccessful_delete: "%{name} could not be deleted."
  errors_were_found: "Errors were found.  Error messages are displayed near each form field below."
  record_is_locked: "The record you are editing is locked by %{name} until %{lock_expiration}."
  
  insta_no_record_found: "<div class=\"fluxx-card-content\"><div class=\"fluxx-card-show\">No record could be found with id %{model_id}.</div></div>"
  insta_no_audit_record_found: "<div class=\"fluxx-card-content\"><div class=\"fluxx-card-show\">No history could be found.</div></div>"
  
  bad_date_format:  "%{date_string} is an invalid format for a date."

  unable_to_promote: "Unable to promote.  These error messages were found: "
  Organization: "Organization"
  organization: "organization"

  date:
    input:
      formats: [:fluxx_long, :fluxx_short, :default, :long, :short]
    formats:
      fluxx_short: "%b %d"
      fluxx_long: "%B %d, %Y"
  time:
    input:
      formats: [:fluxx_long, :fluxx_short, :default, :long, :short]
    formats:
      fluxx_short: "%m/%d/%Y"
      fluxx_long: "%B %d, %Y"
